version: '3.8'
services:
  web:
    container_name: web
    build: ./docker/nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/home/app/staticfiles
    working_dir: /etc/nginx
    links:
      - python
    depends_on:
      - python
  python:
    container_name: python
    build: ./
    command: gunicorn delegadomotos.wsgi:application --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/staticfiles
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    build: ./docker/mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=2003kaio
      - MYSQL_DATABASE=delegadomotos
    healthcheck:
      test: "exit 0"

volumes:
  data-volume:
  static_volume:
