version: '3.8'

services:
  web:
    build: ./delegadomotos
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./delegadomotos/:/usr/src/delegadomotos/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql:8.0.0
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=2003kaio
      - MYSQL_DATABASE=delegadomotos
    healthcheck:
      test: "exit 0"

volumes:
  data-volume: