# Generated by Django 4.1 on 2022-11-03 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de atualização: ')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_sem_fundo', models.ImageField(blank=True, max_length=200, null=True, upload_to='main/')),
                ('imagem_principal', models.ImageField(blank=True, max_length=200, null=True, upload_to='main/')),
                ('imagem1', models.ImageField(blank=True, max_length=200, null=True, upload_to='main/')),
                ('imagem2', models.ImageField(blank=True, max_length=200, null=True, upload_to='main/')),
                ('imagem3', models.ImageField(blank=True, max_length=200, null=True, upload_to='main/')),
                ('imagem4', models.ImageField(blank=True, max_length=200, null=True, upload_to='main/')),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=100)),
                ('freio', models.CharField(max_length=100)),
                ('cilindradas', models.CharField(max_length=100)),
                ('quilometragem', models.CharField(max_length=100)),
                ('partida', models.CharField(max_length=100)),
                ('emplacamento', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.base')),
                ('imagens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.imagens')),
            ],
        ),
    ]
