# Generated by Django 4.1 on 2022-08-15 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('valor_vista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_prazo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=100)),
                ('freio', models.CharField(max_length=100)),
                ('cilindradas', models.CharField(max_length=100)),
                ('quilometragem', models.CharField(max_length=100)),
                ('partida', models.CharField(max_length=100)),
                ('emplacamento', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem_principal', models.ImageField(blank=True, max_length=200, null=True, upload_to='main/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria')),
            ],
        ),
    ]
