# Generated by Django 4.1 on 2022-12-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='is_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
